---
- name: "Generate vhost config for redirects"
  template:
    src: apache_redirects.j2
    dest: "/etc/apache2/sites-available/001-redirects.conf"
  notify: restart apache2

- name: "Enable apache2 vhost for redirects"
  file:
    src: "/etc/apache2/sites-available/001-redirects.conf"
    dest: "/etc/apache2/sites-enabled/001-redirects.conf"
    state: link
  notify: restart apache2
